version: '3'
services:
  prueba:
    build: .
    container_name: contenedordesdedockerfile
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    container_name: contenedordesdedockercompose
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=isen
      - MONGO_INITDB_ROOT_PASSWORD=dwes